server:
  port: 8002
spring:
  application:
    name: consume

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

feign:
  circuitbreaker:
    enabled: true
  hystrix:
    enabled: true



